name: Build and Push to DockerHub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.geogeo532 }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.geogeo532 }}/devops-cv:latest .

      - name: Push to DockerHub
        run: docker push ${{ secrets.geogeo532 }}/devops-cv:latest
